
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

// WEBSOCKET
export const CONNECT_USER = 'CONNECT_USER';

export const GET_MESSAGES = 'GET_MESSAGES';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';